import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Time Table Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Header />
        <div className="flex w-full min-h-dvh">
          <div className="w-1/6 border">
            <h1 className="px-5 py-3 border-b">Home</h1>
            <h1 className="px-5 py-3 border-b">Generate</h1>
          </div>
          <div className="w-5/6">{children}</div>
        </div>
      </body>
    </html>
  );
}
